package user;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;


	@RequestMapping(value = "/add", method = RequestMethod.POST)
	public @ResponseBody String addNewUser (@RequestBody User n) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

        if(userRepository.existsByUserPhone(n.getUserPhone())){
            return "Error: User already Exists";
        }
		userRepository.save(n);
		return "Saved";
	}

	@RequestMapping(value = "/login", method = RequestMethod.POST)
	public @ResponseBody String userLogin (@RequestBody User n) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		if(userRepository.existsByUserPhone(n.getUserPhone())){//phone number exists
			String password = userRepository.findByUserPhone(n.getUserPhone()).getUserPassword();
			if(password.equals(n.getUserPassword()))//password match
				return "Login Successful";
			else
				return "Invalid Password";
		}

		return "Login Unsuccessful: User does not exist";
	}


	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
